<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheMillionthFoodOrderApp.Api\TheMillionthFoodOrderApp.Api.csproj" />
    <ProjectReference Include="..\TheMillionthFoodOrderApp.Infrastructure\TheMillionthFoodOrderApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="*" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.4.0" />
    <PackageReference Include="TUnit" Version="*" />
    <PackageReference Include="TUnit.AspNetCore" Version="*" />
  </ItemGroup>

</Project>
