// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheMillionthFoodOrderApp.Infrastructure.Persistence;

#nullable disable

namespace TheMillionthFoodOrderApp.Infrastructure.Persistence.Migrations.Brand
{
    [DbContext(typeof(BrandDbContext))]
    [Migration("20260610085424_AddOrderTimeSlot")]
    partial class AddOrderTimeSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.BrandSettings.BrandSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(253)
                        .HasColumnType("nvarchar(253)");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("BrandSettings", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategoryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("MenuCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("MenuCategoryTranslations", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifierGroupId");

                    b.ToTable("Modifiers", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ModifierGroups", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroupTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModifierGroupId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ModifierGroupTranslations", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("ModifierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ModifierId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ModifierTranslations", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ProductModifierGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifierGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifierGroupId");

                    b.HasIndex("ProductId", "ModifierGroupId")
                        .IsUnique();

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("IX_ProductModifierGroups_ProductId_SortOrder");

                    b.ToTable("ProductModifierGroups", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderLifecycleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .IsUnique();

                    b.ToTable("OrderLifecycleConfigs", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrderLifecycleConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SystemKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderLifecycleConfigId", "SortOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderStatuses_ConfigId_SortOrder");

                    b.ToTable("OrderStatuses", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatusTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderLifecycleConfigId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromStatusId");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("OrderLifecycleConfigId", "FromStatusId", "ToStatusId")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderStatusTransitions_ConfigId_From_To");

                    b.ToTable("OrderStatusTransitions", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("CustomerFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("nl-BE");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("ReceiptEmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SubtotalGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TableNumber")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("TimeSlotStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("VatRatePercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("IX_Orders_ShopId");

                    b.HasIndex("ShopId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_ShopId_OrderNumber");

                    b.HasIndex("ShopId", "TimeSlotStart")
                        .HasDatabaseName("IX_Orders_ShopId_TimeSlotStart");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitGrossPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitNetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitVatAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.ComboItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComboProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComponentProductId");

                    b.HasIndex("ComboProductId", "ComponentProductId")
                        .IsUnique();

                    b.HasIndex("ComboProductId", "SortOrder");

                    b.ToTable("ComboItems", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Allergens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Allergens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.PrimitiveCollection<string>("DietaryTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DietaryTags");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MenuCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SortOrderInCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId", "SortOrderInCategory")
                        .HasDatabaseName("IX_Products_MenuCategoryId_SortOrderInCategory");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.ProductTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ProductTranslations", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Shops.OpeningHoursTimeBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time(7)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time(7)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopId", "DayOfWeek")
                        .HasDatabaseName("IX_OpeningHoursTimeBlocks_ShopId_DayOfWeek");

                    b.ToTable("OpeningHoursTimeBlocks", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Shops.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("KitchenDisplayEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("PushNotificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SoundAlertEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("TicketPrinterEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Europe/Brussels");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.TaxConfiguration.TaxConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TaxConfigurations", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.TaxConfiguration.VatRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumptionMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("RatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("TaxConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaxConfigurationId", "ConsumptionMode")
                        .IsUnique();

                    b.ToTable("VatRates", (string)null);
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.BrandSettings.BrandSettings", b =>
                {
                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.BrandSettings.BrandColors", "Colors", b1 =>
                        {
                            b1.Property<Guid>("BrandSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Accent")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("Colors_Accent");

                            b1.Property<string>("Primary")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("Colors_Primary");

                            b1.Property<string>("Secondary")
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("Colors_Secondary");

                            b1.HasKey("BrandSettingsId");

                            b1.ToTable("BrandSettings");

                            b1.WithOwner()
                                .HasForeignKey("BrandSettingsId");
                        });

                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.BrandSettings.BrandTypography", "Typography", b1 =>
                        {
                            b1.Property<Guid>("BrandSettingsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BodyFontFamily")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Typography_BodyFontFamily");

                            b1.Property<string>("HeadingFontFamily")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Typography_HeadingFontFamily");

                            b1.HasKey("BrandSettingsId");

                            b1.ToTable("BrandSettings");

                            b1.WithOwner()
                                .HasForeignKey("BrandSettingsId");
                        });

                    b.Navigation("Colors");

                    b.Navigation("Typography");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategoryTranslation", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategory", null)
                        .WithMany("Translations")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.Modifier", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroup", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroupTranslation", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroup", null)
                        .WithMany("Translations")
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierTranslation", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.ModifierGroups.Modifier", null)
                        .WithMany("Translations")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ProductModifierGroup", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroup", null)
                        .WithMany()
                        .HasForeignKey("ModifierGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheMillionthFoodOrderApp.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatus", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderLifecycleConfig", null)
                        .WithMany("Statuses")
                        .HasForeignKey("OrderLifecycleConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatusTransition", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatus", null)
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderLifecycleConfig", null)
                        .WithMany("Transitions")
                        .HasForeignKey("OrderLifecycleConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderStatus", null)
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("TheMillionthFoodOrderApp.Domain.Orders.SelectedModifier", "SelectedModifiers", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ModifierId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ModifierName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<decimal>("PriceAdjustment")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("OrderItemId", "ModifierId");

                            b1.ToTable("OrderItemSelectedModifiers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("SelectedModifiers");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.ComboItem", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.Products.Product", null)
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheMillionthFoodOrderApp.Domain.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ComponentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.Product", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategory", null)
                        .WithMany()
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.Products.Money", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BasePrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BasePrice_Currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("BasePrice")
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.ProductTranslation", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.Products.Product", null)
                        .WithMany("Translations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Shops.OpeningHoursTimeBlock", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.Shops.Shop", null)
                        .WithMany("OpeningHours")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Shops.Shop", b =>
                {
                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.Shops.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_Number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("ShopId");

                            b1.ToTable("Shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.Shops.EatInSettings", "EatIn", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("EatIn_IsEnabled");

                            b1.Property<bool>("RequiresTableNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(true)
                                .HasColumnName("EatIn_RequiresTableNumber");

                            b1.HasKey("ShopId");

                            b1.ToTable("Shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.OwnsOne("TheMillionthFoodOrderApp.Domain.Shops.TimeSlotOrderingSettings", "TimeSlotOrdering", b1 =>
                        {
                            b1.Property<Guid>("ShopId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Interval")
                                .HasColumnType("int")
                                .HasColumnName("TimeSlotOrdering_Interval");

                            b1.Property<bool>("IsEnabled")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false)
                                .HasColumnName("TimeSlotOrdering_IsEnabled");

                            b1.Property<int?>("MaxOrdersPerInterval")
                                .HasColumnType("int")
                                .HasColumnName("TimeSlotOrdering_MaxOrdersPerInterval");

                            b1.HasKey("ShopId");

                            b1.ToTable("Shops");

                            b1.WithOwner()
                                .HasForeignKey("ShopId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("EatIn")
                        .IsRequired();

                    b.Navigation("TimeSlotOrdering")
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.TaxConfiguration.VatRate", b =>
                {
                    b.HasOne("TheMillionthFoodOrderApp.Domain.TaxConfiguration.TaxConfiguration", null)
                        .WithMany("VatRates")
                        .HasForeignKey("TaxConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.MenuCategories.MenuCategory", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.Modifier", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.ModifierGroups.ModifierGroup", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.OrderLifecycle.OrderLifecycleConfig", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Products.Product", b =>
                {
                    b.Navigation("ComboItems");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.Shops.Shop", b =>
                {
                    b.Navigation("OpeningHours");
                });

            modelBuilder.Entity("TheMillionthFoodOrderApp.Domain.TaxConfiguration.TaxConfiguration", b =>
                {
                    b.Navigation("VatRates");
                });
#pragma warning restore 612, 618
        }
    }
}
