<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TheMillionthFoodOrderApp.Application\TheMillionthFoodOrderApp.Application.csproj" />
    <ProjectReference Include="..\TheMillionthFoodOrderApp.Infrastructure\TheMillionthFoodOrderApp.Infrastructure.csproj" />
    <ProjectReference Include="..\TheMillionthFoodOrderApp.ServiceDefaults\TheMillionthFoodOrderApp.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="FastEndpoints" Version="8.0.1" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="WolverineFx" Version="5.19.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
